### ISSUE TITLE
descartes tool0 issue

### ISSUE THREAD

**Issue by hariharan382** [cartesi/descartes-tutorials#22]
I am unable to use descartes with my own cartesian points however i try,i am getting error,
Right now i am getting error " Cannot find transformation to frame 'tool0' in group 'one_leg'."

my group name is "one leg" ,i have changed my endeffector name but i dont know where tool0 is located i checked my full code but i dont know why i am getting this error

![descartes](https://user-images.githubusercontent.com/47359638/130086881-7889ec11-27f3-45e0-9850-5dd4cb08fa15.png)

**Comment by tuler** [comment]
You reached the wrong project bother. Closing the issue.
